---
title: "Older news"
---

* **October 2024**: I chatted with the [Quantum Photonics Club](https://www.facebook.com/qpclub1) on Clubhouse about my work on "Reconstructing networks from simple and complex contagions". Listen to it [here](https://www.youtube.com/watch?v=2NLksRqe2Kw).
* **October 2024**: I gave a talk at the "Spreading on social networks – theory and applications" workshop at Rutgers University. Here are photos of [my talk](assets/images/dimacs_talk.jpeg) and the [group photo](assets/images/dimacs_group_photo.jpeg).
* **October 2024**: "Reconstructing networks from simple and complex contagions" has been published as a letter in [Physical Review E](https://doi.org/10.1103/PhysRevE.110.L042301)!
* **August 2024**: Two new preprints were posted: [one](http://arxiv.org/abs/2408.09223) presenting a theoretical model of a physical reservoir computer and the [other](http://arxiv.org/abs/2408.07755) presenting a new method for efficiently and accurately simulating diffusion processes with a high degree of stochasticity.
* **August 2024**: I [started](https://as.virginia.edu/new-faculty-2024) as an [Assistant Professor of Biology](https://bio.as.virginia.edu/people/nicholas-landry) at the University of Virginia!
* **July 2024**: I moved from Burlington, VT to Charlottesville, VA!
* **June 2024**: I was at [NetSci](https://netsci2024.com) in Quebec City and talked about my [recent work](https://arxiv.org/abs/2405.00129) on network reconstruction and about [XGI](https://xgi.readthedocs.io) at the Software Tools for Network Science [satellite](https://netsci.nascol.net/). My talk on network reconstruction won the [Zachary's Karate Club Trophy](https://networkkarate.tumblr.com/). Here are photos of [my talk](assets/images/zkc_presentation.jpeg) referencing the ZKC network and of the [trophy presentation](assets/images/zkc_award.jpg).
* **May 2024**: Yifei (Bell) Luo, an undergraduate at Middlebury College, co-mentored by [Phil Chodrow](https://www.philchodrow.prof/) and me, presented his undergraduate thesis titled "Efficient sampling of configuration model random hypergraphs"! Very proud of him!
* **April 2024**: I accepted an offer as an Assistant Professor in the [Department of Biology](https://bio.as.virginia.edu/) at the [University of Virginia](https://www.virginia.edu/), as an interdisciplinary hire through the [Contagion Science program](https://contagion-science.virginia.edu/)! I will start in August 2024 and will be looking for a postdoc and several PhD students, so stay tuned!
* **April 2024**: Joint work with [Will Thompson](https://www.willhwthompson.com/), [Laurent Hébert-Dufresne](https://laurenthebertdufresne.github.io/), and [Jean-Gabriel Young](https://www.jgyoung.ca/) titled "Reconstructing networks from simple and complex contagions" is now on [ArXiv](https://arxiv.org/abs/2405.00129)!
* **April 2024**: I was an invited speaker at the [WINQ Program on Complex and Quantum Systems](https://indico.fysik.su.se/event/8139/) workshop in Stockholm, Sweden!
* **April 2024**: I gave a [talk](https://www.youtube.com/watch?v=aK0mFG6WOb4&list=PLBwjIeu8oJrbEhY0zbJq3PKFdcNlj7JKj) at the Interaction Data Lab at LPI Paris on the limitations of models and measures for capturing higher-order structure.
* **March 2024**: Joint work with [Nicole Eikmeier](https://eikmeier.sites.grinnell.edu/) and [Jean-Gabriel Young](https://www.jgyoung.ca/) titled ["The simpliciality of higher-order networks"](/assets/docs/publications/2024_EPJDataSci_simpliciality.pdf) was published in [EPJ Data Science](https://doi.org/10.1140/epjds/s13688-024-00458-1)!
* **March 2024**: I taught a [GNSP topic course](https://march.aps.org/events/higher-order-network-science) on networks with higher-order interactions at the APS March Meeting, along with Ginestra Bianconi and Baruch Barzel. The materials are located on [Github](https://github.com/nwlandry/software-demos/tree/main/marchmeeting2024).
* **February 2024**: Joint work with [Ilya Amburg](https://sites.google.com/site/ilyaamburg1/home), [Mirah Shi](https://www.seas.upenn.edu/~mirahshi/), and [Sinan Aksoy](https://sinanaksoy.com/) titled ["Filtering higher-order datasets"](/assets/docs/publications/2024_JPhysComp_filtering.pdf) was published in the [Journal of Physics: Complexity](https://doi.org/10.1088/2632-072X/ad253a)!
* **December 2023**: I attended the [Complex Networks Winter Workshop](https://vermontcomplexsystems.org/events/cnww/) (CNWW, pronounced "canoe") in Quebec City, QC!
* **November 2023**: XGI-DATA is relaunched on [Zenodo](https://zenodo.org/communities/xgi) with twice as many datasets and now has a corresponding [table of network statistics](https://xgi.readthedocs.io/en/stable/xgi-data.html)!
* **October 2023**: I co-hosted [Yu Tian](https://ytian.netlify.app/) at UVM and had the opportunity to chat science!
* **September 2023**: My work with [Juan G. Restrepo](https://www.colorado.edu/amath/restrepo) titled ["Opinion disparity in hypergraphs with community structure"](/assets/docs/publications/2023_PhysRevE_opinion.pdf) is now out in [Physical Review E](https://doi.org/10.1103/PhysRevE.108.034311)!
* **September 2023**: I gave a talk on "Limitations and opportunities from simple higher-order structural and contagion models" at the [Vermont-KIAS Workshop](https://vermontcomplexsystems.org/events/vermont-kias/) in Burlington, VT.
* **August 2023**: New preprint titled ["The simpliciality of higher-order networks"](https://doi.org/10.48550/arXiv.2308.13918) with [Nicole Eikmeier](https://eikmeier.sites.grinnell.edu/) and [Jean-Gabriel Young](https://www.jgyoung.ca/) is now posted!
* **August 2023**: I organized the [Contagion on Complex Social Systems (CCSS)](https://ccss-conference.github.io/) workshop in Burlington, VT. See the [group photo](assets/images/ccss2023.jpg).
* **July 2023**: I presented ["XGI: A Python package for higher-order interaction networks"](https://doi.org/10.21105/joss.05162) and Nicole Eikmeier presented "The simpliciality of empirical datasets" at NetSci 2023 in Vienna!
* **June 2023**: XGI now supports directed hypergraphs!
* **June 2023**: I attended the Mathematics Research Communities Workshop on [Complex Social Systems](https://www.ams.org/programs/research-communities/2023MRC-SocialSystems). A [photo](assets/images/mrc2023.jpg) of me presenting our project to the rest of the workshop.
* **May 2023**: ["XGI: A Python package for higher-order interaction networks"](https://doi.org/10.21105/joss.05162) is now published in the Journal of Open Source Software!
* **May 2023**: I was an invited speaker at the [Workshop on Modelling and Mining Complex Networks as Hypergraphs](https://math.ryerson.ca/waw2023/).
* **May 2023**: A new preprint with Ilya Amburg, Mirah Shi, and Sinan G. Aksoy entitled "Filtering higher-order datasets" is now on [arXiv](https://doi.org/10.48550/arXiv.2305.06910)!
* **March 2023**: I participated in the [Postdocs in Complexity Conference X](https://www.santafe.edu/events/2023-jsmf-sfi-postdocs-complexity-conference-x).
* **February 2023**: Joint work with [Juan G. Restrepo](https://www.colorado.edu/amath/restrepo), *Polarization in hypergraphs with community structure* is on [ArXiv](https://doi.org/10.48550/arXiv.2302.13967)! A quick summary is [here](/blog/posts/2023-04-30_polarization/index.qmd).
* **January 2023**: Joint work with [jimi adams](https://jimiadams.github.io) on the limitations of using uniplex data representations for modeling multiplex contagion is published in [PLoS ONE](https://doi.org/10.1371/journal.pone.0279345)!
* **January 2023**: I gave a talk at the Network Science Institute at Northeastern.
* **December 2022**: XGI is now a [NumFOCUS](https://numfocus.org/) Affiliated Project!
* **November 2022**: I am now on Mastodon! My username/instance is [nwlandry@mathstodon.xyz](https://mathstodon.xyz/@nwlandry).
* **October 2022**: I gave a demo of XGI and presented in-progress work on the polarizability of hypergraphs with community structure at CCS 2022 in Palma, Spain.
* **October 2022**: I gave an invited talk on the polarizability of hypergraphs with community structure at the AMS Eastern Sectional Meeting in Amherst, MA.
* **August 2022**: Juan G. Restrepo and I organized and chaired the [Contagion on Complex Social Systems workshop](https://www.colorado.edu/amath/caccss2022) in Boulder, CO! [Photo](https://twitter.com/Juanga_Restrepo/status/1558535965517393920)
* **July 2022**: I gave a demo of XGI and presented in-progress work on polarization of hypergraphs with community structure at NetSci 2022.
* **July 2022**: I participated in a hackathon in Portland, ME hosted by NetSci at Northeastern.
* **June 2022**: I started as a postdoctoral research associate at the University of Vermont! Picture of my [first day](assets/images/tgir_first_day.jpg)
* **May 2022**: Joint work with [Juan G. Restrepo](https://www.colorado.edu/amath/restrepo), *Hypergraph assortativity: a dynamical systems perspective* is published in [Chaos](https://doi.org/10.1063/5.0086905) as part of the Dynamics on Networks with Higher-Order Interactions special issue.
* **May 2022**: Joint work with [jimi adams](https://jimiadams.github.io) on the limitations of using uniplex data representations for modeling multiplex contagion is now available on the [ArXiv](https://doi.org/10.48550/arXiv.2204.12348).
* **March 2022**: I gave a talk at NERCCS 2022 on how community structure in hypergraphs can lead to polarization and won Best Oral Presentation.
* **March 2022**: I defended my dissertation and am now a Doctor of Applied Mathematics!
* **February 2022**: I performed in a concert as a member of a 5-piano ensemble!
* **February 2022**: I accepted a postdoctoral position at the University of Vermont, working with the [Complex Systems Center](https://vermontcomplexsystems.org/) and the [TGIR Center](https://www.med.uvm.edu/tgircobre/home) under Jean-Gabriel Young and Laurent Hébert-Dufresne!
* **January 2022**: I presented a poster at *Dynamics Days* on how community structure in hypergraphs can lead to polarization!
* **December 2021**: I gave a talk at the *Canadian Mathematics Society Winter Meeting* on hypergraph assortativity!
* **December 2021**: My article was published in [Physical Review E](https://doi.org/10.1103/PhysRevE.104.064302)!
* **November 2021**: I gave a talk at the *Conference on Complex Networks and their Applications* on hypergraph assortativity!
* **November 2021**: [Leo Torres](https://leotrs.com/) and I released version 0.1 of [XGI](https://github.com/ComplexGroupInteractions/xgi), a Python package for representing and analyzing complex systems with higher-order interactions.
* **September 2021**: Joint work with [Juan G. Restrepo](https://www.colorado.edu/amath/restrepo) was posted on [ArXiv](https://arxiv.org/abs/2109.01099).
* **August 2021**: I became a PhD candidate in Applied Mathematics after passing my comprehensive exam.
* **July 2021**: I gave a talk at Networks 2021 on joint work with [jimi adams](https://jimiadams.github.io/).
* **June 2021**: I gave a talk at TopoNets 2021 (a satellite conference of Networks 2021) on how community structure in hypergraphs can allow polarization to occur.
*  **June 2021**: Sole-authored work was posted on [ArXiv](https://arxiv.org/abs/2106.10384).
* **May 2021**: I gave a talk at the SIAM Dynamical Systems Conference on joint work with Juan Restrepo.
* **May 2021**: I am working as a PhD intern at Pacific Northwest National Laboratory.