---
title:  "Network Science Reading Recs"
date: 2021-03-16
---

This is a list of network science books curated by some fine folks on [Twitter](https://twitter.com/nwlandry/status/1343676490366390272). Note that some of these aren't quite network science related but interesting nonetheless! This isn't an exhaustive list so feel free to email me any other suggestions to add!

* [*Networks, Crowds, and Markets*](https://www.cs.cornell.edu/home/kleinber/networks-book/) by Kleinberg and Easley
* [*Understanding Social Networks: Theories, Concepts, and Findings*](https://global.oup.com/academic/product/understanding-social-networks-9780195379471?cc=us&lang=en&) by Kadushin
* [*The Development of Social Network Analysis: A Study in the Sociology of Science*](https://www.amazon.com/Development-Social-Network-Analysis-Sociology/dp/1594577145) by Freeman
* [*Mathematics of Epidemics on Networks*](https://www.springer.com/gp/book/9783319508047) by Kiss, Miller, and Simon
* [*Fundamentals of Brain Network Analysis*](https://www.sciencedirect.com/book/9780124079083/fundamentals-of-brain-network-analysis) by Fornito, Zalesky, and Bullmore
* [*The Atlas for the Aspiring Network Scientist*](https://arxiv.org/abs/2101.00863) by Coscia
* [*The Human Network: How Your Social Position Determines Your Power, Beliefs, and Behaviors*](https://www.penguinrandomhouse.com/books/541370/the-human-network-by-matthew-o-jackson/) by Jackson
* [*Complex Networks: Principles, Methods and Applications*](https://www.cambridge.org/us/academic/subjects/physics/statistical-physics/complex-networks-principles-methods-and-applications?format=HB&isbn=9781107103184) by Latora, Nicosia, and Russo
* [*Network Science*](http://networksciencebook.com/) by Barabasi
* [*Graph Spectra for Complex Networks*](https://www.cambridge.org/core/books/graph-spectra-for-complex-networks/80472360B29791FDB398259DA4ACA8C4) by Van Mieghem
* [*Networked: The New Social Operating System*](https://mitpress.mit.edu/books/networked) by Rainie and Wellman
* [*Networks*](https://global.oup.com/academic/product/networks-9780198805090?cc=us&lang=en&) by Newman
* [*A First Course in Network Theory*](https://global.oup.com/academic/product/a-first-course-in-network-theory-9780198726463?cc=us&lang=en&) by Estrada and Knight
* [*The Formula: The Universal Laws of Success*](https://www.amazon.com/Formula-Universal-Laws-Success/dp/0316505498) by Barabasi
* [*The Origins of Order: Self-Organization and Selection in Evolution*](https://www.amazon.com/Origins-Order-Self-Organization-Selection-Evolution/dp/0195079515) by Kauffman
* [*Networks: A Very Short Introduction*](https://global.oup.com/academic/product/networks-a-very-short-introduction-9780199588077?cc=us&lang=en&) by Caldarelli and Catanzaro
* [*Quantum Techniques for Stochastic Mechanics*](https://math.ucr.edu/home/baez/networks/) by Baez and Biamonte
* [*A First Course in Network Science*](https://www.cambridge.org/highereducation/books/a-first-course-in-network-science/EE22722F27519D8BB1443C7225C57BAF#overview) by Menczer, Fortunato, and Davis
* [*Dynamical Processes on Complex Networks*](https://doi.org/10.1017/CBO9780511791383) by Barrat, Barth‌élemy, and Vespignani
* [*Evolution of networks*](https://arxiv.org/abs/cond-mat/0106144) by Dorogovtsev and Mendes
* [*Random graphs and complex networks*](https://www.win.tue.nl/~rhofstad/NotesRGCN.pdf) by van der Hofstad
* [*Complex Networks: Structure, Robustness and Function*](https://www.researchgate.net/profile/Shlomo-Havlin/publication/258100764_Complex_Networks_Structure_Robustness_and_Function/links/555b2d8d08ae6fd2d8299a66/Complex-Networks-Structure-Robustness-and-Function.pdf) by Cohen and Havlin
* [Scale-Free Networks: Complex Webs in Nature and Technology](https://global.oup.com/academic/product/scale-free-networks-9780199665174?cc=us&lang=en&) by Caldarelli
* [*Probabilistic Foundations of Statistical Network Analysis*](https://www.amazon.com/Probabilistic-Foundations-Statistical-Monographs-Probability-ebook/dp/B07CGNW9M8) by Crane
* [*Social Network Analysis: Methods and Applications*](https://www.amazon.com/Social-Network-Analysis-Applications-Structural/dp/0521387078) by Wasserman and Faust ([*Cool Visualization*](https://galaxy.opensyllabus.org/#!point/8443905871799))
* [*Distance In Graphs*](https://www.amazon.com/Distance-Graphs-Fred-Buckley/dp/0201095912) by Buckley and Harary
* [*Complex Graphs and Networks*](http://www.math.ucsd.edu/~fan/complex/) by Chung and Lu
* [*Six Degrees: The Science of a Connected Age*](https://www.amazon.com/Six-Degrees-Science-Connected-Age/dp/0393325423) by Watts
* [*Small Worlds: The Dynamics of Networks between Order and Randomness*](https://press.princeton.edu/books/paperback/9780691117041/small-worlds) by Watts
* [*Gathering Social Network Data*](https://us.sagepub.com/en-us/nam/gathering-social-network-data/book260973) by adams
