---
title: "Publications"
---

## Articles

**Nicholas Landry** and Juan G. Restrepo, *Hypergraph community structure and the emergence of polarization*, In Preparation

**Nicholas Landry** and jimi adams, *On limitations of uniplex networks for modeling multiplex diffusion*, Preprint, 2022. [ArXiv:2204.12348](https://doi.org/10.48550/arXiv.2204.12348)

**Nicholas Landry** and Juan G. Restrepo, [*Hypergraph assortativity: a dynamical systems perspective*](/assets/docs/publications/2022_Chaos_hypergraph.pdf), Chaos, 2022. DOI: [10.1063/5.0086905](https://doi.org/10.1063/5.0086905) and [ArXiV:2109.01099](https://doi.org/10.48550/arXiv.2109.01099)

Nicholas Landry, [*Effect of time-dependent infectiousness on epidemic dynamics*](/assets/docs/publications/2021_PhysRevE_effect.pdf), Physical Review E, 2021. DOI: [10.1103/PhysRevE.104.064302](https://doi.org/10.1103/PhysRevE.104.064302) and [ArXiV:2106.10384](https://doi.org/10.48550/arXiv.2106.10384)

**Nicholas Landry** and Juan G. Restrepo, [*The effect of heterogeneity on hypergraph contagion models*](/assets/docs/publications/2020_chaos_effect.pdf), Chaos, 2020. DOI: [10.1063/5.0020034](https://doi.org/10.1063/5.0020034) and [ArXiV:2006.15453](https://doi.org/10.48550/arXiv.2006.15453)

**Nicholas W. Landry** and Marko Knezevic, [*Delineation of First-Order Elastic Property Closures for Hexagonal Metals Using Fast Fourier Transforms*](/assets/docs/publications/2015_materials_delineation.pdf), Materials, 2015. DOI: [10.3390/ma8095303](https://dx.doi.org/10.3390/ma8095303)

Marko Knezevic and **Nicholas W. Landry**, [*Procedures for reducing large datasets of crystal orientations using generalized spherical harmonics*](/assets/docs/publications/2015_MechOfMat_procedures.pdf), Mechanics of Materials, 2015. DOI: [10.1016/j.mechmat.2015.04.014](https://doi.org/10.1016/j.mechmat.2015.04.014)


## Conference Papers

Marko Knezevic, Daniel J. Savage, and **Nicholas W. Landry**, [*Towards Computationally Tractable Simulations of Metal Forming Processes With Evolving Microstructures*](/assets/docs/publications/2014_MSEC_towards.pdf), Proc. ASME., 2014. DOI: [10.1115/MSEC2014-3984](https://doi.org/10.1115/MSEC2014-3984)


## Software

[Comple**X** **G**roup **I**nteractions (XGI)](https://xgi.readthedocs.io): Founder and co-Lead Developer

[HyperContagion](https://hypercontagion.readthedocs.io): Founder and Lead Developer

## Media

[*Interactions Within Larger Social Groups Can Cause Tipping Points in Contagion Flow*](https://publishing.aip.org/publications/latest-content/interactions-within-larger-social-groups-can-cause-tipping-points-in-contagion-flow/), AIP Press Release, October 20th, 2020

[*Contagion on Complex Networks*](https://www.colorado.edu/amath/probably-novel), Radio, Season 3 Episode 13, Probably Novel at University of Colorado Boulder, February 3rd, 2020

## Theses

Nicholas W. Landry, [*Contagion on Complex Systems: Structure and Dynamics*](/assets/docs/Dissertation_Nicholas_W_Landry.pdf), The University of Colorado at Boulder, 2022. ProQuest, ISBN: [9798802733509](https://www.proquest.com/docview/2672014395)

Nicholas W. Landry, [*Computationally Efficient Representation of Statistically Described Material Microstructure for Tractable Forming Simulations*](/assets/docs/senior_final_report.pdf), [The University of New Hampshire](https://scholars.unh.edu/honors/370/), 2014.