---
title:  "Some perspectives on higher-order networks"
date: 2024-02-16
---

Over the past 3ish months, I have, in collaboration with some awesome coauthors, published two papers that express some of my thoughts and ideas surrounding the potential of higher-order networks and the limitations of current modeling practices.

One is titled “Filtering higher-order datasets” and explores the fact that hypergraphs intrinsically encode interactions at different scales and can be used to tease out scale-dependent connection patterns that typically get aggregated out.

The other is titled “The simpliciality of higher-order networks” and was a product of my curiosity on exactly *how* simplicial datasets were and whether it was possible to quantify that in a meaningful way.

Some things I found along the way: higher-order networks---especially empirical ones---contain beautiful structure that not only allows us to ask the same questions as for pairwise networks (What are structurally/dynamically important nodes? Can we partition the network into communities? What is the global structure of a network?) but different ones as well.

For many studies — my own included — “higher-order” networks mean interactions of sizes two and three. Of course, in many empirical datasets, interactions are of a wide range of sizes. As one includes larger and larger interactions, how does that change the structure of a dataset. I think this is an important question and one that I hope to keep digging into.

The other thing that kind of bothered me is that in higher-order network science, there are typically two schools of thought: simplicial complex/computational topology folks and data science hypergraph folks. (This is a parody; the reality of the situation is far more nuanced than this). I hope to try and continue bridging the gap between the hypergraph and simplicial complex worlds and perspectives.

A collaborator once told me that higher-order networks are interesting because, in contrast to pairwise networks, edges have *size*, they can overlap, and they can include one another.